### ISSUE TITLE
Support PMv27.5 Win10 styling

### ISSUE THREAD

**Issue by fofajardo** [FranklinDM/MaterialMoon#4]
The title says it all. The current version of Material Moon and my other themes will stop working when v27.5 arrives but rest assured, I will release a Compatible version before v27.5 gets released.

**Comment by Lootyhoof** [comment]
Just to note: the changes for Win10 in 27.5 will not break existing themes. However, the styling used will make things more stable (since we draw everything ourselves, there's no HiDPI oddness with the caption buttons), but will break compatibility with older versions since there's new CSS media queries introduced.

**Comment by fofajardo** [comment]
I misunderstood the notes for 27.5 and actually thought that it would break the style on Win10 so I proceeded with restricting the current releases to v24, anyways, thanks for the tip.
